### ISSUE TITLE
Prevent inconsistent clarinet config for contracts using the same file

### ISSUE THREAD

**Issue by hugoclrd** [stx-labs/clarinet#1005]
The same clarity file can be used for multiple smart contracts.
In which case, we should probably warn/forbid inconsistent clarinet config with different epoch/version for the same file such as:

```toml
[contracts.ccd002-treasury-nyc-mining]
path = "contracts/extensions/ccd002-treasury.clar"
clarity_version = 2
epoch = 2.1

[contracts.ccd002-treasury-nyc-stacking]
path = "contracts/extensions/ccd002-treasury.clar"
clarity_version = 1
epoch = 2.05
```
