### ISSUE TITLE
Manifest schema refactoring

### ISSUE THREAD

**Issue by lgalabru** [stx-labs/clarinet#554]
Manifests schema could be improved / simplified / cleaned. Some rough ideas:

Before
```toml
[project]
name = "test"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["costs", "pox", "pox-2", "lockup", "costs-2", "cost-voting", "bns"]

[project.cache_location]
path = "./.requirements"
[contracts.test]
contract_path = "contracts/test.clar"
clarity_version = 1
[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
```

After
```toml
[project]
name = "test"
authors = []
description = ""
telemetry = false
cache_location = "./.cache"

[check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[requirements]


[contracts.test]
path = "contracts/test.clar"
clarity_version = 2
```

Should also handle https://github.com/hirosystems/clarinet/issues/417, https://github.com/hirosystems/clarinet/issues/246
